
//AUTOGENERATED FILE: DO NOT EDIT
#include "MINX/Game.h"
#include "MINX/GameTime.h"
#include "MINX/Input/Keyboard.h"
#ifndef MINX_GEMGAME_H_
#define MINX_GEMGAME_H_

using namespace MINX;

namespace MINX_GEMGAME_NS
{
	class MINX_GEMGAME : public Game
	{
		public:
			MINX_GEMGAME();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime * gameTime);
			void Draw(GameTime * gameTime);
	};
}

#endif
